// <auto-generated />
using System;
using Biograf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biograf.Migrations
{
    [DbContext(typeof(BiografContext))]
    partial class BiografContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biograf.Models.Bokning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bokningsnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ForestallningId")
                        .HasColumnType("int");

                    b.Property<string>("KundEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KundNamn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stolnummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Bokningsnummer")
                        .IsUnique();

                    b.HasIndex("ForestallningId", "Stolnummer")
                        .IsUnique();

                    b.ToTable("Bokningar");
                });

            modelBuilder.Entity("Biograf.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Langd")
                        .HasColumnType("int");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Filmer");
                });

            modelBuilder.Entity("Biograf.Models.Forestallning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumTid")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("SalongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalongId");

                    b.ToTable("Forestallningar");
                });

            modelBuilder.Entity("Biograf.Models.Salong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntalStolar")
                        .HasColumnType("int");

                    b.Property<int>("Salongsnummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Salongsnummer")
                        .IsUnique();

                    b.ToTable("Salonger");
                });

            modelBuilder.Entity("Biograf.Models.Bokning", b =>
                {
                    b.HasOne("Biograf.Models.Forestallning", "Forestallning")
                        .WithMany("Bokningar")
                        .HasForeignKey("ForestallningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Forestallning");
                });

            modelBuilder.Entity("Biograf.Models.Forestallning", b =>
                {
                    b.HasOne("Biograf.Models.Film", "Film")
                        .WithMany("Forestallningar")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biograf.Models.Salong", "Salong")
                        .WithMany("Forestallningar")
                        .HasForeignKey("SalongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Salong");
                });

            modelBuilder.Entity("Biograf.Models.Film", b =>
                {
                    b.Navigation("Forestallningar");
                });

            modelBuilder.Entity("Biograf.Models.Forestallning", b =>
                {
                    b.Navigation("Bokningar");
                });

            modelBuilder.Entity("Biograf.Models.Salong", b =>
                {
                    b.Navigation("Forestallningar");
                });
#pragma warning restore 612, 618
        }
    }
}
